#!/bin/bash
#
# Copyright (c) 2021 Wind River Systems, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
dirname=`dirname ${BASH_SOURCE[0]}`
export OECORE_NATIVE_SYSROOT=`realpath $dirname`
export OECORE_TARGET_SYSROOT=`realpath $dirname/../@MACHINE@`
export PATH=$OECORE_NATIVE_SYSROOT/usr/bin/crossscripts:$OECORE_NATIVE_SYSROOT/bin:$OECORE_NATIVE_SYSROOT/usr/bin:$OECORE_NATIVE_SYSROOT/usr/sbin:$PATH

. $OECORE_NATIVE_SYSROOT/environment-setup.d/bash_tab_completion.sh

